server:
  port: 8087

spring:
  application:
    name: blocker
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        service-name: blocker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8180/realms/bank}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
