services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bankApp
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=root
    networks:
      - bank-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/bankApp
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=root
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=8180
    ports:
      - "8180:8180"
    command:
      - start-dev
      - --import-realm
      - -Dkeycloak.import.strategy=OVERWRITE_EXISTING
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - db
    networks:
      - bank-network

  front-ui:
    build:
      context: ./front-ui
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=front-ui
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=O9U5hQ0NApxA8zdIFFxeOkOUwKx8pUhE
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE=authorization_code
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI=http://localhost:8081/login/oauth2/code/keycloak
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE=openid,profile,email
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8180/realms/bank
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_NAME_ATTRIBUTE=preferred_username
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_THYMELEAF_CACHE=false
      - KEYCLOAK_ADMIN_SERVER_URL=http://keycloak:8180
      - KEYCLOAK_ADMIN_REALM=bank
      - KEYCLOAK_ADMIN_CLIENT_ID=admin-cli
      - KEYCLOAK_ADMIN_CLIENT_SECRET=btJdDbNA75MMsTDRybf25u8fGKZwQTtz
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - LOGGING_LEVEL_COM_BANK_FRONT_UI=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      - keycloak
      - exchange-generator
      - exchange
      - transfer
      - cash-service
      - accounts
    networks:
      - bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  exchange-generator:
    build:
      context: ./exchange-generator
      dockerfile: dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=exchange-generator
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=Uppsm320Wyfw2Vn3EDcghnwEP7Dh9TVN
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE=openid
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE=client_credentials
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8180/realms/bank
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI=http://keycloak:8180/realms/bank/protocol/openid-connect/token
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8180/realms/bank
      - EXCHANGE_API_URL=http://exchange-service:8086/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/studyDB?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=19931012
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_COM_BANK_EXCHANGE_GENERATOR=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CLIENT=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      - exchange
      - keycloak
    networks:
      - bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  exchange:
    build:
      context: ./exchange
      dockerfile: dockerfile
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=exchange-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/studyDB?useSSL=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=19931012
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8180/realms/bank
      - KEYCLOAK_REALM=bank
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8180
      - KEYCLOAK_RESOURCE=exchange-service
      - KEYCLOAK_CREDENTIALS_SECRET=9kElCaWDTjcaaWfyjuKItCmyJfdsipgt
      - LOGGING_LEVEL_COM_BANK_EXCHANGE_SERVICE=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      - keycloak
    networks:
      - bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  transfer:
    build:
      context: ./transfer
      dockerfile: dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=transfer-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8180/realms/bank
      - KEYCLOAK_REALM=bank
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8180
      - KEYCLOAK_RESOURCE=transfer-service
      - KEYCLOAK_CREDENTIALS_SECRET=WKgbpjh4kYBBDQ8ayK2lW7MeRLZMlqrb
      - LOGGING_LEVEL_COM_BANK_TRANSFER=DEBUG
      - LOGGING_LEVEL_COM_FASTERXML_JACKSON=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      - keycloak
    networks:
      - bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cash-service:
    build:
      context: ./cash
      dockerfile: dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=cash-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8180/realms/bank
      - KEYCLOAK_REALM=bank
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8180
      - KEYCLOAK_RESOURCE=cash-service
      - KEYCLOAK_CREDENTIALS_SECRET=GIKafEJY32OP8C6k6AfdH2hXuY92vPAt
      - LOGGING_LEVEL_COM_BANK_CASH=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      - keycloak
    networks:
      - bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  accounts:
    build:
      context: ./accounts
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=accounts
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/studyDB?useSSL=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=19931012
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8180/realms/bank
      - KEYCLOAK_REALM=bank
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8180
      - KEYCLOAK_RESOURCE=accounts
      - KEYCLOAK_CREDENTIALS_SECRET=oflL9KgT18jd7iRwLDBFIFDymfqQriM6
      - LOGGING_LEVEL_COM_BANK_ACCOUNTS=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      - keycloak
    networks:
      - bank-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:

networks:
  bank-network:
    driver: bridge