services:
  consul:
    image: hashicorp/consul:1.18
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: consul agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 -bootstrap-expect=1
    volumes:
      - consul_data:/consul/data
    networks:
      - bank-network

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    environment:
      - spring.cloud.consul.host=consul
      - spring.cloud.consul.port=8500
      - KEYCLOAK_REDIRECT_URI=http://host.docker.internal:8090/login/oauth2/code/keycloak
    depends_on:
      - consul
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bank-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bankApp
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=root
    networks:
      - bank-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/bankApp
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=root
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_URL=http://localhost:8180
    ports:
      - "8180:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - db
    networks:
      - bank-network

  exchange-generator:
    build:
      context: ./exchange-generator
      dockerfile: dockerfile
    ports:
      - "8083:8083"
    environment:
      - spring.cloud.consul.host=consul
      - spring.cloud.consul.port=8500
      - ISSUER_URL=http://keycloak:8080/realms/bank
      - EXCHANGE_CLIENT_BASE_URL=http://gateway:8090/api/exchange
    depends_on:
      - consul
    #    extra_hosts:
    #      - "host.docker.internal:host-gateway"
    networks:
      - bank-network

  notifications:
    build:
      context: ./notifications
      dockerfile: dockerfile
    environment:
      - spring.cloud.consul.host=consul
      - spring.cloud.consul.port=8500
      - ISSUER_URL=http://keycloak:8080/realms/bank
    depends_on:
      - consul
      - keycloak
    networks:
      - bank-network

  blocker:
    build:
      context: ./blocker
      dockerfile: dockerfile
    environment:
      - spring.cloud.consul.host=consul
      - spring.cloud.consul.port=8500
      - ISSUER_URL=http://keycloak:8080/realms/bank
    depends_on:
      - consul
      - keycloak
    networks:
      - bank-network

  cash:
    build:
      context: ./cash
      dockerfile: dockerfile
    environment:
      - spring.cloud.consul.host=consul
      - spring.cloud.consul.port=8500
      - ISSUER_URL=http://keycloak:8080/realms/bank
      - USER_CLIENT_BASE_URL=http://gateway:8090/api/accounts
      - BLOCKER_CLIENT_BASE_URL=http://gateway:8090/api/blocker
      - NOTIFICATION_CLIENT_BASE_URL=http://gateway:8090/api/notification
    depends_on:
      - consul
      - keycloak
#      - accounts
    networks:
      - bank-network

  exchange:
    build:
      context: ./exchange
      dockerfile: dockerfile
    ports:
      - "8086:8086"
    environment:
      - spring.cloud.consul.host=consul
      - spring.cloud.consul.port=8500
      - ISSUER_URL=http://keycloak:8080/realms/bank
    depends_on:
      - consul
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bank-network


  front-ui:
    build:
      context: ./front-ui
      dockerfile: dockerfile
    environment:
      - ISSUER_URL=http://host.docker.internal:8180/realms/bank
      - USER_CLIENT_BASE_URL=http://gateway:8090/api/accounts
      - EXCHANGE_CLIENT_BASE_URL=http://gateway:8090/api/exchange
    #    depends_on:
    #      - keycloak
    #      - consul
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bank-network

volumes:
  consul_data:

networks:
  bank-network:
    driver: bridge