services:

  consul:
    image: hashicorp/consul:1.18
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: consul agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 -bootstrap-expect=1
    volumes:
      - consul_data:/consul/data
    networks:
      - bank-network

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - consul
    networks:
      - bank-network



  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bankApp
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=root
    networks:
      - bank-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/bankApp
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=root
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME=localhost
    ports:
      - "8180:8080"
    command:
      - start-dev
      - --import-realm
      - -Dkeycloak.import.strategy=OVERWRITE_EXISTING
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - db
    networks:
      - bank-network



  front-ui:
    build:
      context: ./front-ui
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=api-gateway
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=t0GNfKIjwDNOZdeMyP9nX2gjc7EA7c7e
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE=authorization_code
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE=openid,profile,email
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/bank
    depends_on:
      - keycloak
      - consul
    #      - exchange-generator
    #      - exchange
    #      - transfer
    #      - cash-service
    #      - accounts
    networks:
      - bank-network

volumes:
  mysql_data:
  consul_data:

networks:
  bank-network:
    driver: bridge