server:
  port: 8081
spring:
  application:
    name: front-ui

  config:
    import: "optional:consul"

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: t0GNfKIjwDNOZdeMyP9nX2gjc7EA7c7e
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/bank
            user-name-attribute: preferred_username

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG
    org.springframework.cloud.consul: INFO
