server:
  port: 8081

spring:
  application:
    name: front-ui
  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        service-name: front-ui

  thymeleaf:
    cache: false


  security:
    oauth2:
      client:
        provider:
          my-provider-keycloak:
            issuer-uri: http://localhost:8180/realms/bank
        registration:
          keycloak:
            authorizationGrantType: authorization_code
            provider: my-provider-keycloak
            client-id: api-gateway
            client-secret: t0GNfKIjwDNOZdeMyP9nX2gjc7EA7c7e
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
clients:
  user-client:
    base-url: ${USER_CLIENT_BASE_URL:http://localhost:8090/api/v1/accounts/me}
  transfer-client:
    base-url: ${TRANSFER_CLIENT_BASE_URL:http://localhost:8090/api/transfers}
  cash-client:
    base-url: ${CASH_CLIENT_BASE_URL:http://localhost:8090/api/cash}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG