server:
  port: 8083
spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: exchange-generator
            client-secret: Uppsm320Wyfw2Vn3EDcghnwEP7Dh9TVN
            scope: openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/bank
            token-uri: http://localhost:8180/realms/bank/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank
exchange:
  api-url: http://localhost:8086