server:
  port: 8083

spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank
  keycloak:
    realm: bank
    auth-server-url: http://localhost:8180
    resource: exchange-generator
    credentials:
      secret: Uppsm320Wyfw2Vn3EDcghnwEP7Dh9TVN
